### ISSUE TITLE
关于运行

### ISSUE THREAD

**Issue by stephanlianyi** [xhuz/yys-robot#1]
作者你好  很创新的用node创建脚本的方式 
我运行cpm run compole 出线两行分别是 
> yys-auto@1.0.0 ***
> tsc
之后就无事发生
请问正确操作是什么？谢谢

**Comment by xhuz** [comment]
要确保npm安装了所有依赖，运行编译，根据需求运行bat文件。这就是正确的操作方式readme中写的很清楚了。该版本目前已经老旧过时，就算运行成功也不一定能正常挂机。你有兴趣可以fork一份，自己开发，或者等我后续更新
